### ISSUE TITLE
"mvn package" command hangs

### ISSUE THREAD

**Issue by othias** [kefik/Sokoban4J#1]
Hi, I tried to build the main Sokoban4J package and this is what happens:

mvn package
[INFO] Scanning for projects...
Downloading: http://diana.ms.mff.cuni.cz:8081/artifactory/repo/cz/cuni/amis/amis-pom/0.0.1-SNAPSHOT/maven-metadata.xml

And the command just times out...

**Comment by kefik** [comment]
Hi, should be working now... still experiencing problems? We had some problems with hackers a few days back + there was some serious DNS outage in Central Europe. 

Link: http://diana.ms.mff.cuni.cz:8081/artifactory/repo/cz/cuni/amis/amis-pom/0.0.1-SNAPSHOT/maven-metadata.xml
Is accessible from my browser.

Cheers!
